<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Statussen extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Statussen_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'statussen/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'statussen/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'statussen/index.html';
            $config['first_url'] = base_url() . 'statussen/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Statussen_model->total_rows($q);
        $statussen = $this->Statussen_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'statussen_data' => $statussen,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('statussen/statussen_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Statussen_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'staDescription' => $row->staDescription,
	    );
            $this->load->view('statussen/statussen_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('statussen'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('statussen/create_action'),
	    'id' => set_value('id'),
	    'staDescription' => set_value('staDescription'),
	);
        $this->load->view('statussen/statussen_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'staDescription' => $this->input->post('staDescription',TRUE),
	    );

            $this->Statussen_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('statussen'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Statussen_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('statussen/update_action'),
		'id' => set_value('id', $row->id),
		'staDescription' => set_value('staDescription', $row->staDescription),
	    );
            $this->load->view('statussen/statussen_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('statussen'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'staDescription' => $this->input->post('staDescription',TRUE),
	    );

            $this->Statussen_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('statussen'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Statussen_model->get_by_id($id);

        if ($row) {
            $this->Statussen_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('statussen'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('statussen'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('staDescription', 'stadescription', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Statussen.php */
/* Location: ./application/controllers/Statussen.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-02-18 09:50:38 */
/* http://harviacode.com */